"""product media table

Revision ID: 7bb7eb83e6b3
Revises: 6afc5c1b62c1
Create Date: 2025-11-19 19:21:54.605952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bb7eb83e6b3'
down_revision: Union[str, None] = '6afc5c1b62c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_media_id', table_name='product_media')
    op.drop_table('product_media')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_type', postgresql.ENUM('IMAGE', 'VIDEO', name='mediatype'), autoincrement=False, nullable=False),
    sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('s3_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_media_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_media_pkey')
    )
    op.create_index('ix_product_media_id', 'product_media', ['id'], unique=False)
    # ### end Alembic commands ###

