"""add_updated_user_id_to_product_model

Revision ID: ae7f79b83819
Revises: c6aad98b66ff
Create Date: 2025-11-20 09:03:16.924099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7f79b83819'
down_revision: Union[str, None] = 'c6aad98b66ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['updated_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'updated_by_id')
    # ### end Alembic commands ###

