"""add_created_by_id_to_products

Revision ID: ed50ad5e8ebe
Revises: fc1727965ca7
Create Date: 2025-11-19 09:52:55.866982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed50ad5e8ebe'
down_revision: Union[str, None] = 'fc1727965ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'created_by_id')
    # ### end Alembic commands ###

